bit operations

In [1]:
import numpy as np
import random
from scipy.signal import find_peaks

In [1]:
a = 10  ## 1010
b = 5   ## 0101
print(f"Bit-wise AND {a & b}")
print(f"Bit-wise OR {a | b}")
print(f"Bit-wise XOR {a ^ b}")
print(f"Bit-wise right shift {a >> 1}")
print(f"Right shit twice {a >> 2}")
print(f"Left shift {a << 1}")
print(f"Left shift twice {a << 2}")

Bit-wise AND 0
Bit-wise OR 15
Bit-wise XOR 15
Bit-wise right shift 5
Right shit twice 2
Left shift 20
Left shift twice 40


In [6]:
userId = 1005
uidb = [(userId >> 8 ) & 0xFF, userId & 0xFF]
print(uidb)

[3, 237]


In [21]:
bits = []
for b in uidb:
    for i in range(7, -1, -1):
        bits.append( (b >> i) & 1 )
print(bits)
print(np.array(bits, dtype=np.uint8))

[0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1]
[0 0 0 0 0 0 1 1 1 1 1 0 1 1 0 1]


In [23]:
a = np.arange(10)
b = np.arange(10).tolist()
print(a, type(a))
print(b, type(b))

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9] <class 'list'>


In [19]:
random.seed(1)
da = [random.randint(0,255) for _ in range(10)]
print(da)

[68, 32, 130, 60, 253, 230, 241, 194, 107, 48]


In [23]:
rng = random.Random(1)
data = [rng.randint(0,255) for _ in range(100)]
print(data)

[68, 32, 130, 60, 253, 230, 241, 194, 107, 48, 249, 14, 199, 221, 1, 228, 136, 117, 52, 162, 15, 11, 13, 4, 195, 110, 216, 14, 113, 224, 253, 119, 176, 118, 112, 235, 148, 11, 213, 51, 95, 151, 61, 170, 216, 97, 155, 145, 255, 201, 17, 245, 124, 206, 212, 88, 187, 191, 44, 224, 55, 83, 201, 189, 250, 15, 240, 22, 157, 201, 87, 86, 116, 6, 102, 118, 207, 176, 180, 235, 137, 2, 196, 66, 105, 218, 28, 246, 186, 102, 211, 248, 182, 212, 177, 0, 169, 234, 14, 117]


In [27]:
print(20//8)
print(20/8)
print(20%8)

2
2.5
4


In [39]:
a = [np.random.randint(2) for _ in range(40)]
print(a)
aB = ''.join( map(str, a[0:8]) )
print(aB)
aB = int( ''.join( map(str, a[0:8]) ), 2 )
print(aB)

[0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1]
00001001
9


In [53]:
a = np.array([1, 0, 1, 0]*4)
print(a)
out = np.correlate(a, [1, 0, 1, 0])
print(out)
peaks, _= find_peaks(out)
print(peaks)
print(out[peaks])

[1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
[2 0 2 0 2 0 2 0 2 0 2 0 2]
[ 2  4  6  8 10]
[2 2 2 2 2]


In [ ]:
a = np.array([1, 0, 1, 0,] * 4 + [1, 0, 1, 1] + [1, 0, 1, 0,] * 4 + [1, 0, 1, 1])
print(a)
corOut = np.correlate(a, np.array( [1,0,1,0]*2) )
print(corOut)

[170 170 170 170]
[340 340 340 340 340]


In [9]:
a = [1]
l = 4
b = np.arange(10)
print(b[l:l+len(a)])

[4]


In [9]:
l = []
print(len(l))
if True:
    print(True)

0
True


In [10]:
for i in range(10):
    if i == 4:
        continue
    print(i)

0
1
2
3
5
6
7
8
9


In [28]:
pathLoss = 0.01
chCoeff = np.sqrt(pathLoss) * ( np.sqrt(1/2) * ( np.random.randn(10000) + 1j*np.random.randn(10000) ) )
print(f"Mean Channel Power: {np.mean(np.abs(chCoeff)**2)}")

Mean Channel Power: 0.010158949112789023


In [32]:
from collections import Counter
import random

random.seed(45)
counts = Counter()
for _ in range(1000000):
    active = random.sample(range(1, 21), 2)
    counts.update(active)
print(counts)

Counter({7: 100834, 6: 100513, 16: 100427, 5: 100212, 9: 100189, 19: 100128, 13: 100113, 11: 100104, 8: 100067, 20: 100054, 12: 99972, 10: 99942, 3: 99929, 14: 99748, 2: 99738, 18: 99685, 15: 99628, 17: 99602, 1: 99559, 4: 99556})
